version: 2
updates:
  # Maintain the Pipeline
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns: ["*"]

  # Maintain the Infrastructure (Terraform)
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      providers:
        patterns: ["*"]

  # Maintain Tooling (Python)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
