name: "Reusable Static Analysis"

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: "."
        type: string
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: read

jobs:
  validate:
    name: "Tfctl Doctor & Security"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Consumer Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkout Central Policies
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: BT-IT-Infrastructure-CloudOps/aws-workflows
          path: _central_policies
          sparse-checkout: |
            policies
          token: ${{ secrets.GH_PAT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_wrapper: false

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'

      - name: Install Tfctl
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          pip install --upgrade pip
          pip install "git+https://${GH_TOKEN}@github.com/BT-IT-Infrastructure-CloudOps/tfctl.git@main"

      - name: Run Doctor
        working-directory: ${{ inputs.working-directory }}
        # Point tfctl to the downloaded central policies
        run: tfctl doctor --policy-path $GITHUB_WORKSPACE/_central_policies/policies
