name: "Reusable TFCTL Plan"

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      AWS_ROLE_ARN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Tools (Python/TF)
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_wrapper: false

      - name: Install Tfctl
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          pip install --upgrade pip
          pip install "git+https://${GH_TOKEN}@github.com/BT-IT-Infrastructure-CloudOps/tfctl.git@main"

      - name: Run TFCTL Plan
        working-directory: ${{ inputs.working-directory }}
        # TFCTL handles init, workspace selection, and plan generation
        run: tfctl plan --out tfplan.binary

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: tfplan-${{ inputs.environment }}
          path: ${{ inputs.working-directory }}/tfplan.binary
          retention-days: 1
